### ISSUE TITLE
support free form request body

### ISSUE THREAD

**Issue by liuming** [takumakanari/embulk-input-http#12]
It is a legit use case when requesting an HTTP endpoint that doesn't accept regular form parameters as input but instead accepts a proprietary or standard payload, such as a chunk of JSON.

In those cases, one may need to specify it's own body like this:
```yaml
request_body: |
  {"key": "value"}
```

**Comment by takumakanari** [comment]
Hi @liuming , thanks for your creating issue. I'll think about it later.

**Comment by liuming** [comment]
@takumakanari thanks for the reply. I would have provided a pull request if I still remember how to write Java 😄

**Comment by takumakanari** [comment]
I wonder whether `request_body` property have a dynamic-value or not?
If yes, need to think about how to configure it on yaml.

**Comment by liuming** [comment]
I think the short answer is no. The long answer is I understand there'll be use cases for that, but if it allows having dynamic values then it'll also require to configured in those values in other YAML nodes, then still the actual values will need to be injected while composing the YAML. So for those case, I can see it'll be easier to push the responsibility to whoever/whatever compose or generate the YAML file. Plus in the end, you can always take iterations, to make request_body static-only at first, then if more solid use cases come up, you can enhance the design to support dynamic values. The bottom line is: It's easier to keep the current design simple and wait until more use cases appear then add more complexity to the design. It's not easy to do the other way around: That you added something not really needed at the early stage and figure it won't satisfy the future use cases, because once the API/design is published, you can't really take it back.

**Comment by takumakanari** [comment]
Thanks for your opinions, also I agree with you 👍

**Comment by pygillier** [comment]
Hi, 

I also need to use freeform request body. Can you release a new version  of plugin ?

**Comment by takumakanari** [comment]
@pygillier I see, I'll do it tomorrow morning (JST).

**Comment by takumakanari** [comment]
@liuming @pygillier I've just released `v0.0.20` to support this feature. Apologize for my operation late.
