### ISSUE TITLE
"package" gradlew task is not supported

### ISSUE THREAD

**Issue by koooge** [takumakanari/embulk-input-http#8]
Hello.
I tried to build this plugin, and I typed `./gradlew package`.
But it diplayed BUILD FAILED message.
cf. http://www.embulk.org/docs/customization.html#step-2-building-the-project

```
$ ./gradlew tasks

...
Other tasks
-----------
checkstyle
gem

Rurles
...
```

This seems that this gradlew doesn't include the "package" task.
*embulk-input-http* should be upgraded embulk version. 😇

**Comment by takumakanari** [comment]
Hi, Thanks for your report.
I've just fixed an issue. Can you try it again?

**Comment by koooge** [comment]
BUILD SCCESSFUL :+1:
